### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by davidvilanova** [jchen1981/GMPR#1]
Hello,
Could you give an example with some repdoucible data on how to use it ??

thanks.

**Comment by jchen1981** [comment]
See 'GMPR.example.R' for two examples of using GMPR size factors

**Comment by davidvilanova** [comment]
Thanks for uploading the examples using DESeq.  We´ll test it properly.
Do you have a similar example using metagenomeSEQ ?
Thanks.
