### ISSUE TITLE
Normalized counts

### ISSUE THREAD

**Issue by davidvilanova** [jchen1981/GMPR#2]
Hi,
I´trying to get the normalized counts after using GMPR.

```
...
dds <- DESeq(dds,parallel=TRUE)

# GMPR factors
otu.tab <- GMPR(counts(dds,norm=FALSE),intersect.no=10)
gmpr.size.factor <- otu.tab$gmpr
sizeFactors(dds) <-  gmpr.size.factor
dds <- estimateDispersions(dds)

# Get normalized
mdat <- counts(dds, normalized=TRUE)

```

Is the DESeq counts the best way to get normalized counts ?

**Comment by jchen1981** [comment]
Yes,  counts(dds, normalized=TRUE) scales the counts by the size factors.
You could simply use

otu.tab <- counts(dds,norm=FALSE)

size.factor <- GMPR(otu.tab, intersect.no=10)

otu.tab <- t(t(otu.tab) / size.factor)


As we discussed in the GMPR paper (https://peerj.com/articles/4600/),
GMPR-normalized data are most useful for taxon-level analysis. It may
not have an advantage for alpha and beta-diversity analysis.

Best,

Jun

**Comment by davidvilanova** [comment]
Thanks Jun,

I had to modify the script as follows to make it work. The example provided in the example file is failing for me.

```
otu.tab <- counts(dds,norm=FALSE)

size.factor <- GMPR(otu.tab,intersect.no=10)

sizeFactors(dds) <-  size.factor$gmpr

otu.tab <- t(t(otu.tab) / size.factor$gmpr)

```
Thanks,
Best,
david

**Comment by jchen1981** [comment]
Thanks for catching the mistake!
