### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by ramongallego** [jchen1981/GMPR#3]
Hi there,

Just wondering whether GMPR is a contained R package that I should install (so far both `devtools::install_github("https://github.com/jchen1981/GMPR")` and `devtools::install_local("~/Downloads/GMPR_0.1.3.tar.gz")` returned errors. It would be great if you could update the README file with some installation instructions

Cheers

**Comment by jchen1981** [comment]
I have added the instruction

To install it, download the package, open a terminal, and type "R CMD
INSTALL GMPR_0.1.3.tar.gz"


Best,

Jun
